name: GLaDOS Checkin
on:
  workflow_dispatch: # 允许手动点击执行   
  schedule:
    - cron: '30 0 * * *' # 每天UTC时间0:30（北京时间早上8:30）自动运行
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: 
          python -m pip install --upgrade pip
          pip install requests
      - name: Run Checkin Scrript
        env:
          GR_COOKIE: ${{secrets.GR_COOKIE}}
        run: python checkin.py  
